name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do Ubuntu
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          libgtk2.0-0 \
          libgtk-3-0 \
          libnotify-dev \
          libnss3 \
          libxss1 \
          libasound2t64 \
          libxtst6 \
          xauth \
          xvfb

      - name: Instalar dependências do projeto
        run: npm ci

      - name: Definir TERM
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Rodar testes E2E
        run: npx cypress run --browser electron --spec ""cypress/e2e/*.cy.js""